### ISSUE TITLE
make GetMetadataForPackage public so we can use your documentation

### ISSUE THREAD

**Issue by keilwastaken** [needle-mirror/com.unity.xr.management#1]
hello in your documentation you have a method of GetMetadataForPackage to get meta data of a package. currently this is an internal method so it is unaccessible if you are trying to use it. or update this part of the documentation as we cannot use the methods provided 
```

var metadata = XRPackageMetadataStore.GetMetadataForPackage(my_pacakge_id);
    assets = AssetDatabase.FindAssets($"t:{metadata.settingsType}");
    var assetPath = AssetDatabase.GUIDToAssetPath(assets[0]);

    // Settings access is type specific. You will need information from your plug-in documentation
    // to know how to get at specific instances and properties.

    // You must know the type of the settings you are accessing.
    var directInstance  = AssetDatabase.LoadAssetAtPath(assetPath, typeof(full.typename.for.pluginsettings));

    // You must know the access method for getting build target specific settings data.
    var buildTargetSettings = directInstance.GetSettingsForBuildTargetGroup(BuildTargetGroup.Android);

    // Do something with settings...

    // Mark instance dirty and save any changes.
    EditorUtility.SetDirty(directInstance);
    AssetDatabase.SaveAssets();
```

**Comment by marwie** [comment]
Hello @keilwastaken 

Please report this issue to Unity directly (you can report issues at the bottom of the documentation pages) as this repo is really just a mirror of package releases and not offially supported by Unity so it is unlikely that anyone at Unity will fix/read your issue if you report it here at the moment :(
https://docs.unity3d.com/Packages/com.unity.xr.management@3.2/manual/EndUser.html
